services:
  primboo:
    build: .
    container_name: primboo-digital
    restart: unless-stopped
    env_file:
      - .env.local
    ports:
      - "9191:3000"
    volumes:
      - uploads:/app/uploads

volumes:
  uploads:
